import { useState, type FormEvent } from 'react';
import { BrowserRouter, Link, useLocation, useNavigate } from 'react-router-dom';
import { id, now, type DirectorRecord, type Domain, type Message, type PersistedState, type Project, type Source } from './domain';
import { repository } from './repository';
import { getModels, requestDirector } from './runtime';
import './director.css';

type Draft = { sources: Source[]; prompt: string; promptId?: string; projectId?: string; title: string };
const emptyDraft = (): Draft => ({ sources: [], prompt: '', title: '' });
const displayDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
const labelFor = (record: DirectorRecord) => record.kind === 'feedback' ? record.source.name : `${record.sources.length} sources`;
const recommendations = (text: string, count: number) => text.split('\n').filter((line) => /^\s*(\d+\.|#\d+)/.test(line)).slice(0, count).map((line) => line.replace(/^\s*(\d+\.|#\d+)\s*/, ''));

export default function App() { return <BrowserRouter><DirectorApp /></BrowserRouter>; }

function DirectorApp() {
  const [state, setState] = useState<PersistedState>(() => repository.load());
  const [quick, setQuick] = useState<DirectorRecord | null>(null);
  const [projectModal, setProjectModal] = useState<Project | null | undefined>(undefined);
  const location = useLocation();
  const route = location.pathname; const domain: Domain = route.includes('design-studio') ? 'design' : 'photography';
  const saveProject = (draft: Omit<Project, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }) => setState(repository.saveProject(state, draft));
  let content: React.ReactNode;
  if (route === '/compare') content = <Workflow key="compare" kind="compare" domain="photography" state={state} onState={setState} />;
  else if (route === '/darkroom' || route === '/design-studio') content = <Library domain={domain} state={state} onQuick={setQuick} />;
  else if (route === '/compare-library') content = <Library domain="photography" kind="compare" state={state} onQuick={setQuick} />;
  else if (route === '/projects') content = <Projects state={state} onQuick={setQuick} onProject={setProjectModal} />;
  else if (route === '/prompts') content = <Prompts state={state} onState={setState} />;
  else if (route === '/settings') content = <SettingsPanel state={state} onState={setState} />;
  else content = <Workflow key="feedback" kind="feedback" domain="photography" state={state} onState={setState} />;
  return <><Shell>{content}</Shell>{quick && <QuickView record={quick} project={state.projects.find((entry) => entry.id === quick.projectId)} onClose={() => setQuick(null)} />}{projectModal !== undefined && <ProjectModal initial={projectModal} onClose={() => setProjectModal(undefined)} onSave={(draft) => { saveProject(draft); setProjectModal(undefined); }} />}</>;
}

function Shell({ children }: { children: React.ReactNode }) {
  const location = useLocation(); const nav = [['Director', '/'], ['Design Studio', '/design-studio'], ['Darkroom', '/darkroom'], ['Compare', '/compare-library'], ['Projects', '/projects'], ['Prompts', '/prompts'], ['Settings', '/settings']];
  return <main className="director-frame"><aside className="sidebar"><div className="wordmark">DIRECTOR<span> V4</span></div><nav>{nav.map(([name, href]) => <Link key={href} to={href} className={location.pathname === href || (href === '/compare-library' && location.pathname === '/compare') ? 'active' : ''}>{name}</Link>)}</nav><p className="sidebar-note">Creative intelligence,<br />locally configured.</p></aside><section className="surface">{children}</section></main>;
}

function Workflow({ kind, domain, state, onState }: { kind: 'feedback' | 'compare'; domain: Domain; state: PersistedState; onState: (state: PersistedState) => void }) {
  const navigate = useNavigate(); const [draft, setDraft] = useState<Draft>(emptyDraft); const [phase, setPhase] = useState<'new' | 'generating' | 'completed'>('new'); const [record, setRecord] = useState<DirectorRecord | null>(null); const [error, setError] = useState(''); const [chatText, setChatText] = useState('');
  const allowed = kind === 'feedback' ? draft.sources.length === 1 : draft.sources.length >= 2 && draft.sources.length <= 6; const model = kind === 'feedback' ? (draft.sources.length && state.settings.visionModel ? state.settings.visionModel : state.settings.feedbackModel) : state.settings.compareModel;
  const selectFiles = async (files: FileList | null) => { if (!files) return; const chosen = await Promise.all(Array.from(files).slice(0, kind === 'compare' ? 6 : 1).map(async (file) => ({ id: id(), name: file.name, type: file.type || 'Image', size: file.size, preview: await new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }) }))); setDraft((current) => ({ ...current, sources: kind === 'compare' ? chosen : chosen.slice(0, 1), title: chosen[0]?.name || current.title })); };
  const run = async () => { if (!allowed) return; setError(''); setPhase('generating'); try { const result = await requestDirector(state.settings, model, kind, draft.prompt || 'Give a useful, precise critique.', draft.sources); const stamp = now(); const base = { id: id(), domain, title: draft.title || draft.sources[0].name, prompt: draft.prompt, promptId: draft.promptId, model, projectId: draft.projectId, result, favourite: false, chat: [] as Message[], createdAt: stamp, updatedAt: stamp }; setRecord(kind === 'feedback' ? { ...base, kind, source: draft.sources[0] } : { ...base, kind, sources: draft.sources, recommendations: recommendations(result, draft.sources.length) }); setPhase('completed'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Director could not complete this request.'); setPhase('new'); } };
  const persist = () => { if (record) { onState(repository.saveRecord(state, record)); navigate(record.kind === 'compare' ? '/compare-library' : domain === 'design' ? '/design-studio' : '/darkroom'); } };
  const sendChat = async (event: FormEvent) => { event.preventDefault(); if (!record || !chatText.trim()) return; const user: Message = { id: id(), role: 'user', text: chatText.trim(), createdAt: now() }; setChatText(''); const working = { ...record, chat: [...record.chat, user], updatedAt: now() }; setRecord(working); try { const response = await requestDirector(state.settings, record.model, 'chat', user.text, record.kind === 'feedback' ? [record.source] : record.sources, working.chat); setRecord((current) => current ? { ...current, chat: [...current.chat, { id: id(), role: 'assistant', text: response, createdAt: now() }], updatedAt: now() } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Chat request failed.'); } };
  return <><PageHeader eyebrow={kind === 'feedback' ? 'DIRECTOR / FEEDBACK + CHAT' : 'DIRECTOR / COMPARE'} title={phase === 'new' ? (kind === 'feedback' ? 'New Feedback' : 'New Comparison') : record?.title || 'Director is working'} action={phase === 'completed' ? <button className="button primary" onClick={persist}>SAVE {kind === 'feedback' ? 'FEEDBACK' : 'COMPARISON'}</button> : undefined} />
    {phase === 'new' && <section className="workflow-grid"><section className="card form-card"><div className="section-label">SOURCE {kind === 'compare' ? '(2–6)' : ''}</div><label className="dropzone"><input type="file" accept="image/*" multiple={kind === 'compare'} onChange={(event) => void selectFiles(event.target.files)} /><span>{draft.sources.length ? `${draft.sources.length} source${draft.sources.length > 1 ? 's' : ''} selected` : 'Drop image files here or click to browse'}</span><small>{kind === 'compare' ? 'Select between 2 and 6 sources.' : 'One source is required.'}</small></label>{draft.sources.length > 0 && <div className="source-list">{draft.sources.map((source) => <div className="source-row" key={source.id}>{source.preview && <img src={source.preview} alt="" />}<span>{source.name}</span><button onClick={() => setDraft((current) => ({ ...current, sources: current.sources.filter((entry) => entry.id !== source.id) }))}>×</button></div>)}</div>}<label>Source type<select value={domain} disabled><option>{domain === 'design' ? 'Design / screen / layout' : 'Photography'}</option></select></label><label>Project link<select value={draft.projectId || ''} onChange={(event) => setDraft({ ...draft, projectId: event.target.value || undefined })}><option value="">No project</option>{state.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label></section><section className="card form-card"><div className="section-label">REVIEW BRIEF</div><label>Saved prompt<select value={draft.promptId || ''} onChange={(event) => { const prompt = state.prompts.find((entry) => entry.id === event.target.value); setDraft({ ...draft, promptId: prompt?.id, prompt: prompt?.body || draft.prompt }); }}><option value="">Custom brief</option>{state.prompts.filter((prompt) => !prompt.archived && (prompt.useType === 'both' || prompt.useType === kind)).map((prompt) => <option key={prompt.id} value={prompt.id}>{prompt.name}</option>)}</select></label><label>Prompt<textarea value={draft.prompt} placeholder="Tell Director what to focus on…" onChange={(event) => setDraft({ ...draft, prompt: event.target.value, promptId: undefined })} /></label><div className="model-line">MODEL <span>{model || 'Not configured'}</span></div>{error && <p className="error">{error}</p>}<button className="button primary wide" disabled={!allowed} onClick={() => void run()}>{kind === 'feedback' ? 'GET FEEDBACK' : 'COMPARE SOURCES'}</button>{kind === 'compare' && <button className="button quiet wide" onClick={() => { setDraft(emptyDraft()); setError(''); }}>CLEAR</button>}</section></section>}
    {phase === 'generating' && <section className="thinking card"><div className="thinking-orb" /><div><div className="section-label">DIRECTOR IS THINKING</div><h2>{kind === 'feedback' ? 'Reading your source…' : 'Comparing your sources…'}</h2><p>This request is running against your configured local model. You can wait here while it completes.</p></div></section>}
    {phase === 'completed' && record && <RecordResult record={record} projects={state.projects} onRecord={setRecord} onChat={sendChat} chatText={chatText} setChatText={setChatText} error={error} onNew={() => { setDraft(emptyDraft()); setRecord(null); setError(''); setPhase('new'); }} />}</>;
}

function RecordResult({ record, projects, onRecord, onChat, chatText, setChatText, error, onNew }: { record: DirectorRecord; projects: Project[]; onRecord: (record: DirectorRecord) => void; onChat: (event: FormEvent) => void; chatText: string; setChatText: (value: string) => void; error: string; onNew: () => void }) { return <section className="result-stack"><article className="card result"><div className="result-meta"><span>{record.kind === 'feedback' ? record.source.type : `${record.sources.length} SOURCES`}</span><span>{record.model}</span><span>{projects.find((project) => project.id === record.projectId)?.title || 'UNLINKED'}</span></div><div className="result-body"><h2>{record.kind === 'feedback' ? 'Feedback' : 'Comparison read'}</h2><p className="prewrap">{record.result}</p>{record.kind === 'compare' && record.recommendations.length > 0 && <ol className="recommendations">{record.recommendations.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ol>}</div><div className="result-actions"><button className="button quiet" onClick={() => onRecord({ ...record, favourite: !record.favourite, updatedAt: now() })}>{record.favourite ? '★ FAVOURITED' : '☆ FAVOURITE'}</button><button className="button quiet" onClick={onNew}>NEW {record.kind === 'feedback' ? 'FEEDBACK' : 'COMPARISON'}</button></div></article><article className="card chat"><div className="section-label">ASK DIRECTOR</div><div className="chat-log">{record.chat.length === 0 ? <p className="muted">Continue this specific review with a contextual question.</p> : record.chat.map((message) => <div className={`message ${message.role}`} key={message.id}>{message.text}</div>)}</div><form onSubmit={onChat}><input value={chatText} onChange={(event) => setChatText(event.target.value)} placeholder="Ask about this result…" /><button className="button primary" type="submit">SEND</button></form>{error && <p className="error">{error}</p>}</article></section>; }

function PageHeader({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <header className="page-header"><div><div className="section-label">{eyebrow}</div><h1>{title}</h1></div>{action}</header>; }

function Library({ domain, kind, state, onQuick }: { domain: Domain; kind?: 'feedback' | 'compare'; state: PersistedState; onQuick: (record: DirectorRecord) => void }) {
  const navigate = useNavigate(); const records = state.records.filter((record) => record.domain === domain && (!kind || record.kind === kind)); const name = kind === 'compare' ? 'Compare Library' : domain === 'design' ? 'Design Studio' : 'Darkroom';
  return <><PageHeader eyebrow={name.toUpperCase()} title={kind === 'compare' ? 'Saved comparisons' : `${domain === 'design' ? 'Design' : 'Photography'} feedback`} action={<button className="button primary" onClick={() => navigate(kind === 'compare' ? '/compare' : '/')}>ADD NEW {kind === 'compare' ? 'COMPARISON' : 'FEEDBACK'}</button>} /><section className="library">{records.length === 0 ? <div className="empty card"><div className="section-label">NO SAVED RECORDS</div><h2>Your completed work will live here.</h2><p>Saved feedback and comparisons appear in this library without duplicating fixture cards.</p></div> : records.map((record) => <RecordCard key={record.id} record={record} project={state.projects.find((project) => project.id === record.projectId)} onClick={() => onQuick(record)} />)}</section></>;
}

function RecordCard({ record, project, onClick }: { record: DirectorRecord; project?: Project; onClick: () => void }) { return <button className="record-card card" onClick={onClick}><div className="record-card-top"><span>{record.kind.toUpperCase()}</span><span>{displayDate(record.updatedAt)}</span></div><h2>{record.title}</h2><p>{labelFor(record)}</p><div className="record-card-bottom"><span>{project?.title || 'Unlinked'}</span><span>{record.favourite ? '★' : 'VIEW'}</span></div></button>; }

function QuickView({ record, project, onClose }: { record: DirectorRecord; project?: Project; onClose: () => void }) {
  const navigate = useNavigate(); return <div className="overlay" role="dialog" aria-modal="true"><aside className="quick-drawer"><button className="drawer-close" onClick={onClose}>×</button><div className="section-label">QUICK VIEW</div><h2>{record.title}</h2><dl><div><dt>TYPE</dt><dd>{record.kind}</dd></div><div><dt>PROJECT</dt><dd>{project?.title || 'Unlinked'}</dd></div><div><dt>PROMPT</dt><dd>{record.prompt || 'No custom brief'}</dd></div></dl><p className="quick-excerpt">{record.result.slice(0, 420)}{record.result.length > 420 ? '…' : ''}</p><button className="button primary wide" onClick={() => { onClose(); navigate(record.kind === 'compare' ? '/compare-library' : record.domain === 'design' ? '/design-studio' : '/darkroom'); }}>VIEW FULL {record.kind === 'compare' ? 'COMPARISON' : 'FEEDBACK'}</button></aside></div>;
}

function Projects({ state, onQuick, onProject }: { state: PersistedState; onQuick: (record: DirectorRecord) => void; onProject: (project: Project | null) => void }) {
  const [selected, setSelected] = useState<string | null>(null); const project = state.projects.find((entry) => entry.id === selected); const linked = project ? state.records.filter((record) => record.projectId === project.id) : [];
  if (project) return <><PageHeader eyebrow="PROJECTS" title={project.title} action={<><button className="button quiet" onClick={() => onProject(project)}>EDIT PROJECT</button><button className="button primary" onClick={() => setSelected(null)}>BACK TO PROJECTS</button></>} /><div className="tabs"><span className="active">OVERVIEW</span><span>FEEDBACK ({linked.length})</span><span>NOTES</span></div><section className="project-summary card"><div><div className="section-label">{project.type}</div><p>{project.description || 'No project description yet.'}</p></div><div className="metric"><b>{linked.length}</b><span>LINKED RECORDS</span></div></section><section className="library compact">{linked.length ? linked.map((record) => <RecordCard key={record.id} record={record} onClick={() => onQuick(record)} />) : <div className="empty card">No feedback or comparisons are linked to this project yet.</div>}</section></>;
  return <><PageHeader eyebrow="PROJECTS" title="Projects" action={<button className="button primary" onClick={() => onProject(null)}>ADD NEW PROJECT</button>} /><section className="library">{state.projects.length === 0 ? <div className="empty card">Create a project to group feedback and comparisons without copying their records.</div> : state.projects.map((entry) => <button key={entry.id} className="record-card card" onClick={() => setSelected(entry.id)}><div className="record-card-top"><span>{entry.type}</span><span>{state.records.filter((record) => record.projectId === entry.id).length} RECORDS</span></div><h2>{entry.title}</h2><p>{entry.description || 'No description'}</p><div className="record-card-bottom"><span>UPDATED {displayDate(entry.updatedAt)}</span><span>VIEW PROJECT</span></div></button>)}</section></>;
}

function ProjectModal({ initial, onClose, onSave }: { initial: Project | null; onClose: () => void; onSave: (draft: Omit<Project, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }) => void }) {
  const [title, setTitle] = useState(initial?.title || ''); const [type, setType] = useState(initial?.type || 'Project'); const [description, setDescription] = useState(initial?.description || '');
  return <div className="overlay modal-layer" role="dialog" aria-modal="true"><form className="modal card" onSubmit={(event) => { event.preventDefault(); if (title.trim()) onSave({ id: initial?.id, title: title.trim(), type, description }); }}><div className="section-label">PROJECT SETTINGS</div><h2>{initial ? 'Edit project' : 'New project'}</h2><label>Title<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Type<input value={type} onChange={(event) => setType(event.target.value)} /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="modal-actions"><button className="button quiet" type="button" onClick={onClose}>CANCEL</button><button className="button primary" type="submit">SAVE PROJECT</button></div></form></div>;
}

function Prompts({ state, onState }: { state: PersistedState; onState: (state: PersistedState) => void }) {
  const [editing, setEditing] = useState<typeof state.prompts[number] | null>(null); const [search, setSearch] = useState(''); const visible = state.prompts.filter((prompt) => !prompt.archived && `${prompt.name} ${prompt.category}`.toLowerCase().includes(search.toLowerCase()));
  const save = (draft: { id?: string; name: string; category: string; useType: 'feedback' | 'compare' | 'both'; description: string; body: string; systemNote?: string; archived: boolean }) => { onState(repository.savePrompt(state, draft)); setEditing(null); };
  return <><PageHeader eyebrow="PROMPTS" title="Prompt Library" action={<button className="button primary" onClick={() => setEditing({ id: '', name: '', category: 'General', useType: 'both', description: '', body: '', systemNote: '', archived: false, createdAt: '', updatedAt: '' })}>ADD PROMPT</button>} /><div className="toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search prompts" /><span>{visible.length} ACTIVE</span></div><section className="library">{visible.length ? visible.map((prompt) => <button className="record-card card" key={prompt.id} onClick={() => setEditing(prompt)}><div className="record-card-top"><span>{prompt.category}</span><span>{prompt.useType}</span></div><h2>{prompt.name}</h2><p>{prompt.description || prompt.body}</p><div className="record-card-bottom"><span>PERSISTENT PRESET</span><span>EDIT</span></div></button>) : <div className="empty card">No active prompts. Add one here, or use a custom brief in a workflow.</div>}</section>{editing && <PromptModal initial={editing.id ? editing : null} onClose={() => setEditing(null)} onSave={save} />}</>;
}

function PromptModal({ initial, onClose, onSave }: { initial: { id: string; name: string; category: string; useType: 'feedback' | 'compare' | 'both'; description: string; body: string; systemNote?: string; archived: boolean } | null; onClose: () => void; onSave: (draft: { id?: string; name: string; category: string; useType: 'feedback' | 'compare' | 'both'; description: string; body: string; systemNote?: string; archived: boolean }) => void }) {
  const [draft, setDraft] = useState({ id: initial?.id || '', name: initial?.name || '', category: initial?.category || 'General', useType: initial?.useType || 'both', description: initial?.description || '', body: initial?.body || '', systemNote: initial?.systemNote || '', archived: initial?.archived || false });
  return <div className="overlay modal-layer"><form className="modal card prompt-modal" onSubmit={(event) => { event.preventDefault(); if (draft.name.trim() && draft.body.trim()) onSave({ ...draft, id: draft.id || undefined }); }}><div className="section-label">PROMPT EDITOR</div><h2>{initial ? 'Edit prompt' : 'New prompt'}</h2><label>Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><div className="two-fields"><label>Category<input value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></label><label>Use type<select value={draft.useType} onChange={(event) => setDraft({ ...draft, useType: event.target.value as typeof draft.useType })}><option value="both">Feedback + Compare</option><option value="feedback">Feedback</option><option value="compare">Compare</option></select></label></div><label>Description<input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><label>Prompt body<textarea value={draft.body} onChange={(event) => setDraft({ ...draft, body: event.target.value })} /></label><label>System note<input value={draft.systemNote} onChange={(event) => setDraft({ ...draft, systemNote: event.target.value })} /></label><div className="modal-actions"><button type="button" className="button quiet" onClick={onClose}>CANCEL</button>{initial && <button type="button" className="button quiet" onClick={() => onSave({ ...draft, archived: !draft.archived })}>{draft.archived ? 'RESTORE' : 'ARCHIVE'}</button>}<button className="button primary">SAVE PROMPT</button></div></form></div>;
}

function SettingsPanel({ state, onState }: { state: PersistedState; onState: (state: PersistedState) => void }) {
  const [models, setModels] = useState<string[]>([]); const [status, setStatus] = useState(''); const change = <K extends keyof typeof state.settings>(key: K, value: typeof state.settings[K]) => onState(repository.update(state, { settings: { ...state.settings, [key]: value } }));
  const test = async () => { setStatus('Testing connection…'); try { const found = await getModels(state.settings); setModels(found); setStatus(`Connected — ${found.length} model${found.length === 1 ? '' : 's'} available.`); } catch (reason) { setStatus(reason instanceof Error ? reason.message : 'Connection test failed.'); } };
  return <><PageHeader eyebrow="SETTINGS" title="Director preferences" /><section className="settings-grid"><article className="card form-card"><div className="section-label">PERSONALISATION</div><label>Base style<select value={state.settings.baseStyle} onChange={(event) => change('baseStyle', event.target.value as typeof state.settings.baseStyle)}><option>Professional</option><option>Friendly</option><option>Candid</option></select></label><label>Warmth<select value={state.settings.warmth} onChange={(event) => change('warmth', event.target.value as typeof state.settings.warmth)}><option>Less</option><option>Neutral</option><option>More</option></select></label><label className="check"><input type="checkbox" checked={state.settings.fastAnswers} onChange={(event) => change('fastAnswers', event.target.checked)} />Fast Answers</label><label>Custom instructions<textarea value={state.settings.customInstructions} onChange={(event) => change('customInstructions', event.target.value)} /></label></article><article className="card form-card"><div className="section-label">LOCAL MODEL RUNTIME</div><label>OpenAI-compatible server URL<input value={state.settings.serverUrl} onChange={(event) => change('serverUrl', event.target.value)} /></label><button className="button quiet" onClick={() => void test()}>TEST CONNECTION</button>{status && <p className={status.startsWith('Connected') ? 'success' : 'error'}>{status}</p>}<label>Feedback model<select value={state.settings.feedbackModel} onChange={(event) => change('feedbackModel', event.target.value)}><option value="">Select model</option>{models.map((model) => <option key={model}>{model}</option>)}</select></label><label>Compare model<select value={state.settings.compareModel} onChange={(event) => change('compareModel', event.target.value)}><option value="">Select model</option>{models.map((model) => <option key={model}>{model}</option>)}</select></label><label>Vision model<select value={state.settings.visionModel} onChange={(event) => change('visionModel', event.target.value)}><option value="">Select model</option>{models.map((model) => <option key={model}>{model}</option>)}</select></label></article></section></>;
}
